---
format: "html"
---

## Module 1: Introductions

Lessons and Labs:

1. [Introduction to Data Science Processes and Roles](./M1/lessons/01_intro.qmd)
2. [Lab 1: Confirmatory Data Analysis (CDA)- blind typing experiment](./M1/lessons/02_lab_cda_blind_typing.ipynb)
3. [Lab 2: Exploratory Data Analysis (EDA)- US Census 2010-2019](./M1/lessons/03_lab_eda_census.ipynb)

Exercises:

1. [John Snow](./M1/exercises/john_snow.qmd) (3 questions)

## Module 2: Data Wrangling

1. [Pandas](./M2/lessons/01_pandas.ipynb) (external links)
2. [Lab 1: Bike Sharing](./M2/lessons/02_lab_bike_sharing.ipynb)
3. [Lab 2: Pandas' Function application](./M2/lessons/03_pandas_function_application.ipynb)

Exercises:

1. [Pandas Exercises](./M2/exercises/pandas_exercises.ipynb) (34 question)

## Module 3: Descriptive Statistics

1. [Statistical Analysis](./M3/lessons/01_statistics.ipynb)
2. [Python Visualization Tools](./M3/lessons/02_viz_tools.ipynb)
3. [Visualizing distributions of data](./M3/lessons/03_displot.ipynb)
4. [Visualizing categorical data](./M3/lessons/04_catplot.ipynb)
5. [Visualizing statistical relationships](./M3/lessons/05_relplot.ipynb)
6. [Effective communication of exploratory results](./M3/lessons/06_effective_viz.ipynb)

Exercises:

1. [Visualization Exercises](./M3/exercises/viz_exercises.ipynb) (4 questions)
2. [EDA Penguins](./M3/exercises/eda_penguins_ex.ipynb) (7 questions)

## Module 4: Inferential Statistics

1. [Hypothesis Testing](./M4/lessons/01_hypothesis_testing.ipynb)
2. [Categorical Association](./M4/lessons/02_cat_association.ipynb)
3. [Numerical Correlation](./M4/lessons/03_num_correlation.ipynb)

Exercises:

1. [Hypothesis Testing](./M4/exercises/hypothesis_ex.ipynb) (3 questions)